# this compiles all Rmds  and fills ./public in hugo_source

#blogdown::build_site()
#blogdown:::build_rmds("content/post/2020-12-30-jacks_car_rental_gym.Rmd")
#blogdown:::build_rmds("content/post/2021_03_07_qlearning_frozenlake_convergence.Rmd")
#blogdown:::build_rmds("content/post/2021-05-02-workflow_scientific_papers.Rmd")
#blogdown:::build_rmds("content/post/2021_05_14_covid_rapid_test_reliability.Rmd")
#blogdown:::build_rmds("content/post/2021_12_30_fumbbl_dataset.Rmd")

############################################################
# https://bookdown.org/yihui/blogdown/local-preview.html

#If you have time-consuming code chunks in any Rmd files, you have to use either of these methods to save time:
# Do not call build_site(), but blogdown::hugo_build() instead. 
# The latter does not compile any Rmd files, but simply runs the hugo command to build the site. 
# Please use this method only if you are sure that your Rmd files do not need to be recompiled.


blogdown::hugo_build()
print("site build")
# The mode local = TRUE is primarily for blogdown::serve_site() to serve the website locally. 
#Draft and future posts are always rendered when local = TRUE, but not when local = FALSE. 
# This is for you to preview draft and future posts locally. 
# If you know the Hugo command line, it means the hugo command is called with the flags -D -F, or equivalently, --buildDrafts --buildFuture.
blogdown::serve_site()
blogdown::stop_server()

#If your website does not work without the full baseurl, or you do not want the draft or future posts to be published, 
#you should not publish the public/ directory generated by serve_site(). 
#Always run blogdown::hugo_build() before you upload this directory to a web server.

blogdown::hugo_build()
print("site build")

# If your drafts and future posts contain (time-)sensitive information, you are strongly recommended to 
# delete the /public/ directory before you rebuild the site for publishing every time, because Hugo never deletes it, 
# and your sensitive information may be rendered by a certain blogdown::hugo_build() call last time and left in the directory.

# Nb public folder staat NIET onder versie beheer.